### ISSUE TITLE
Missing input file reported

### ISSUE THREAD

**Issue by diossynvax** [hcgasser/CAPE#3]
Hi 

I'm trying to follow the tutorial. I've installed all the dependencies and created the input file 'HIV-1_nef.fasta' and placed it ${CAPE}/data/raw/

However, when I ran the command 

./cape.py --domain $DOMAIN --task data_create_support --DATA \"HIV_nef\"

I get the following error below, looking for the TRAIN.fasta file.

Is there a stage where the HIV-1_nef.fasta is split into testing, train and validation data that I am currently missing?

BW

Matthew

Startup with args: Namespace(task='data_create_support', job='AUTO', domain='HIV_nef', env='py', device='cuda', debug=None) 2024-05-09 09:09:51:  Using CUDA device: Tesla V100-SXM2-16GB
                      Number of CUDA devices: 1
                      Current CUDA device: 0
                      CUDA version: 11.7
                      PyTorch version: 2.0.1+cu117
                      cuDNN version: 8500
ENV.PROJECT: '/CAPE'
2024-05-09 09:09:51:  created directory: /CAPE/artefacts/CAPE
Load task file: /CAPE/configs/CAPE/tasks/data_create_support.yaml
Traceback (most recent call last):
  File "/CAPE/./cape.py", line 45, in <module>
    module.run()
  File "/CAPE/libs/CAPE/handler/data.py", line 47, in run
    kit.bioinf.fasta.read_fasta(
  File "/CAPE/libs/kit/bioinf/fasta.py", line 37, in read_fasta
    with open(filename, "r", encoding=encoding) as file:
FileNotFoundError: [Errno 2] No such file or directory: '/CAPE/data/input/HIV_nef_full/TRAIN.fasta'
> /CAPE/libs/kit/bioinf/fasta.py(37)read_fasta()
-> with open(filename, "r", encoding=encoding) as file:

**Comment by hcgasser** [comment]
Hi, have you run the command "./cape.py --domain $DOMAIN --task data_raw_to_input" before?

**Comment by diossynvax** [comment]
I have but I'm afraid that also produces that I've not yet been able to resolve (see below).

```

./cape.py --domain $DOMAIN --task data_raw_to_input
Startup with args: Namespace(task='data_raw_to_input', job='AUTO', domain='HIV_nef', env='py', device='cuda', debug=None) 2024-05-09 14:54:15:  Using CUDA device: Tesla V100-SXM2-16GB
                      Number of CUDA devices: 1
                      Current CUDA device: 0
                      CUDA version: 11.7
                      PyTorch version: 2.0.1+cu117
                      cuDNN version: 8500
ENV.PROJECT: '/CAPE'
Load task file: /CAPE/configs/CAPE/tasks/data_raw_to_input.yaml
DATA (input gets evaluated): "HIV_nef"       
Traceback (most recent call last):
  File "/CAPE/./cape.py", line 64, in <module>
    module.run()
  File "/CAPE/libs/CAPE/handler/data.py", line 15, in run
    kit.load_dhparams(G.TASK.DHPARAMS, doc_idx=1)
  File "/CAPE/libs/kit/__init__.py", line 210, in load_dhparams
    G.DHPARAMS = DD.from_yaml(dhparams, **kwargs)
  File "/CAPE/libs/kit/data/dd.py", line 36, in from_yaml
    x = x.evaluate(**kwargs)
  File "/CAPE/libs/kit/data/dd.py", line 122, in evaluate
    this[key] = eval(value)
  File "<string>", line 1, in <module>
NameError: name 'join' is not defined
> <string>(1)<module>()
(Pdb)

**Comment by hcgasser** [comment]
Sorry - you are correct. There were issues with the pre-trained replication files. I have added another commit to fix this. Please just perform a 'git pull' outside the docker container in the repository folder. The docker container accesses this, so it should be automatically updated in the container.

**Comment by diossynvax** [comment]
Thank you, that seems to have fixed the problem but I'm afraid the outputted TRAIN/TEST/VAL files are all empty. Could I just check with you, have I downloaded the HIV-1_nef.fasta file into the correct gapped format? I've attached a truncated file as an example.
[HIV-1_nef.fasta.txt](https://github.com/hcgasser/CAPE/files/15266720/HIV-1_nef.fasta.txt)

**Comment by hcgasser** [comment]
The file you sent is aligned (empty places are filled with '-'), however, it should be unaligned. The following download options should work:
![image](https://github.com/hcgasser/CAPE/assets/15750734/adf7a3b4-497a-4d8f-a00b-029124daa9c3)
Also, I assume the ending was just added during truncation (it has to be .fasta). 
Since sequences get added into the database, you won't exactly use the same sequences as were used in the paper

**Comment by diossynvax** [comment]
Thank you, I've downloaded the file in the correct format and I'm now able to generate the correct output. Thank you for all your help, I'll now close the issue.
