### ISSUE TITLE
Hyper-parameter search - Altering protein sequence length

### ISSUE THREAD

**Issue by diossynvax** [hcgasser/CAPE#6]
Hello

I'd like to run a hyper-parameter search using my own dataset, where the maximum protein length is significantly longer than the trial data (a maximum of 575 amino acids). Could you tell me which parameters in which files I would need to adjust to accommodate the greater protein length?

Best wishes

Matthew

**Comment by hcgasser** [comment]
Hi Matthew,
The file configs/CAPE/dhparams/HIV_nef.yaml specifies the data. The field MAX_SEQ_LEN tells the model what the length of the maximum sequence is - this should be longer than the longest sequence. Under FILTER, there is a MIN and MAX value. These are used in the data preparation step to discard sequences outside these lengths.
Please let me know if you have any further questions.
All the best,

Hans

**Comment by hcgasser** [comment]
Also... Probably better to add a few tokens as spares (e.g. stop token)

**Comment by diossynvax** [comment]
Thank you as always for a fast reply.

I followed your suggestion and then tried to subsequently generate sequences based on the search. However, I seem to have run into a new problem but I'm not quite sure what's causing it.


> /CAPE/libs/kit/nn/transformer.py(61)forward()
-> k = torch.concat([hidden[0], k], dim=-2)  # (B, T, C)
(Pdb) ../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1093: indexSelectSmallIndex: block: [0,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

**Comment by hcgasser** [comment]
Ok. Have you run a hyp search with the Nef protein before and did it work? Also, did you follow the instructions from ./cape.py --domain $DOMAIN --task data_raw_to_input onwards?

**Comment by hcgasser** [comment]
Would make sense to change the $DOMAIN variable in this case to separate the results from the Nef ones

**Comment by diossynvax** [comment]
I did run a hyp search and assigned a separate domain name. I will run the hyp search again to see if that was the issue.

**Comment by hcgasser** [comment]
Another thing to check could be whether there are any non standard amino acids in your dataset

**Comment by hcgasser** [comment]
(might make sense to make a test run with a very small dummy dataset)

**Comment by diossynvax** [comment]
Thank you, that seems to have resolved it.
